export const TAPES=[
{t:"TAPE 0 — 'don't follow the hum'",x:"Day 11. The hum is 120hz. It stops when IT is near. If the lights buzz, run. — K."},
{t:"TAPE 1 — garage dogs",x:"They blindfolded the hounds once. They still found us by our shoes squeaking. Walk. — M."},
{t:"TAPE 2 — pipe crew",x:"We lost the 15A fuse down the hot tunnel. Exit needs two. Don't drink the pipe water. — R."},
{t:"TAPE 3 — smiler light",x:"Smiler froze under my flashlight for 4 seconds. Batteries = life. Hoard them. — J."},
{t:"TAPE 6 — party",x:"If you hear balloons, kill your light? No — RUN. They see heat. Slide is behind the cake. — =("},
{t:"TAPE 9 — shadow self",x:"It stands where you stood 10 seconds ago. Never stop moving. Nightvision shows it green. — V."},
{t:"TAPE 33 — last train",x:"The metro still runs for something. 3 fuses. Don't look at windows. Look at the floor. — conductor"},
{t:"TAPE ! — mama",x:"She sings happy birthday with 3 voices. Shotgun works. Repellent works. Grief doesn't. — survivor"},
{t:"TAPE ?? — dev note",x:"If you're reading this, the vending machine on Level 4 takes BACKCOINS. Also: up up down down. You didn't hear it from me. — dev"},
];
export const INTROS={
T:"Training room. Small, lit, safe. Learn the moves — everything here stays here.",
0:"You fell through the floor at work. Carpet. Hum. Yellow.",
1:"Concrete. Fog. Something pants in the dark.",
2:"Heat. Pipes. The exit door is dead without fuses.",
3:"Breakers hum. Teeth grin where the wires hang.",
4:"Cubicles forever. Something sleeps in arm-piles.",
5:"Check-in is eternal. Your room key glows faintly.",
6:"Your flashlight sputters. Balloons squeak nearby.",
7:"Chlorine and tile. The deep hole calls.",
8:"RED HALLS. SHE IS AWAKE. RUN.",
9:"No light. No sound. Your shadow walks without you.",
10:"Cake. Balloons. Smiles. All lies. Fight through.",
11:"A train idles with no driver. Power it. Leave.",
12:"Endless motion. Windows pass but never stop.",
13:"Sermon halls. Static prays where the speakers hang.",
14:"Tiled bathrooms. Something knocks from inside stalls.",
"∞":"Purple dark. Every item you ever wanted. And SHE is awake.",
SB:"White room. No rules. Press X and play god.",
};
export const ACHIEVE={
firstblood:{name:"First Blood",desc:"Kill any entity"},
mama:{name:"Mama Down",desc:"Kill Mama Party"},
pacifist:{name:"Ghost",desc:"Escape a level with 0 kills"},
rich:{name:"Hoarder",desc:"Hold 20 backcoins"},
crafter:{name:"Tinkerer",desc:"Craft anything"},
quartermaster:{name:"Quartermaster",desc:"Open 3 military crates"},
guide:{name:"Guided",desc:"Meet The Guide"},
konami:{name:"Up Up",desc:"Enter the old code"},
seeker:{name:"Golden Gut",desc:"Find the Golden Almond"},
friend:{name:"Be Kind",desc:"Accept the Guide's gift"},
disco:{name:"DJ Backrooms",desc:"Click the title 7 times"},
mother:{name:"Nest Empty",desc:"Kill the Mother of All Entities"},
};
